---
# tasks file for postgrey
- name: "Package"
  package:
    name: '{{ item }}'
  with_items:
    - '{{ postgrey_packages }}'
  tags:
    - postgrey
    - packages

- name: "Options"
  lineinfile:
    path: '/etc/default/postgrey'
    regexp: '^POSTGREY_OPTS='
    line: 'POSTGREY_OPTS="{{ postgrey_opts }}"'
  notify: postgrey restart
  tags:
    - postgrey
    - options

- name: "local whitelist clients"
  template:
    src: 'whitelist_clients.j2'
    dest: '/etc/postgrey/whitelist_clients.local'
    owner: root
    group: root
    mode: 0644
  when:
    - postgrey_whitelist_clients is defined
  notify: postgrey restart
...
